---
- hosts: devstack
  vars_files: 
    - zuul-params.yaml

  tasks:
    - name: Include variables from job_vars/{{ zuul_project | basename }}.yaml
      include_vars: "job_vars/{{ zuul_project | basename }}.yaml"
      failed_when: False
      tags: always

    - name: Include variables from job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml"
      when: job_type is defined
      failed_when: False
      tags: always

    - name: Set persistent saving for journald
      ini_file:
        path: /etc/systemd/journald.conf
        section: Journal
        option: Storage
        value: persistent
      become: True
      tags: journald-log

    - name: Restart systemd-journald service
      service:
        name: systemd-journald
        state: restarted
      become: True
      tags: journald-log

    - include: tasks/devstack/run-unstack.yaml

    - include: tasks/devstack/install-apt-packages.yaml
    - include: tasks/devstack/install-pip.yaml
    - include: tasks/devstack/configure-pip-index.yaml
    - include: tasks/devstack/install-python-packages.yaml

    - include: tasks/devstack/find-data-port.yaml
      #    - include: tasks/devstack/configure-ovs.yaml

    - include: tasks/devstack/install-zuul.yaml
    - include: tasks/devstack/prepare-git-repos.yaml

    - include: tasks/devstack/upper-constraints-mods.yaml
      with_items: "{{ upper_constraints_pinning }}"
      when: upper_constraints_pinning is defined

    - name: Applying cherry-picks
      cb_cherry_pick_devstack:
        url: "{{ git_server }}/{{ item.project }}"
        ref: "{{ item.patches }}"
        path: "{{ item.path }}"
      with_items: "{{ cherry_picks }}"
      when: cherry_picks is defined
      become: True
      tags: cherry-pick

    - include: tasks/devstack/install-networking-hyperv.yaml

    - include: tasks/devstack/write-configs.yaml

    - include: tasks/devstack/run-stack.yaml
