- hosts: ad
  gather_facts: yes
  vars_files: 
    - zuul-params.yaml
    - group_vars/windows

  tasks:

  - name: Include variables from job_vars/{{ zuul_project | basename }}.yaml
    include_vars: "job_vars/{{ zuul_project | basename }}.yaml"
    failed_when: False
    tags: always

  - name: Include variables from job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml
    include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml"
    when: job_type is defined
    failed_when: False
    tags: always

  - name: Disable firewall for Domain, Public and Private profiles
    win_firewall:
      state: disabled
      profiles:
      - Domain
      - Private
      - Public
    tags: disable_firewall

  - name: Set administrator password to {{ ansible_ssh_pass }}
    win_shell: "net user administrator {{ ansible_ssh_pass }}"

  - name: Configure AD domain {{ ad_domain }}
    win_domain:
      dns_domain_name: "{{ ad_domain }}"
      safe_mode_password: "{{ ansible_ssh_pass }}"
    register: ad_create

  - name: Reboot after creating domain
    win_reboot:
    when: ad_create.reboot_required is defined and ad_create.reboot_required
