---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - zuul-params.yaml

  tasks:
    - name: Include variables from job_vars/{{ zuul_project | basename }}.yaml
      include_vars: "job_vars/{{ zuul_project | basename }}.yaml"
      failed_when: False
      tags: always

    - name: Include variables from job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml"
      when: job_type is defined
      failed_when: False
      tags: always

    - name: Configure compute node trunk
      include_tasks: tasks/configure-compute-trunk.yaml
      with_items: "{{ groups['all'] }}"

- hosts: win2016-cinder
  vars_files:
    - zuul-params.yaml
    - group_vars/windows

  tasks:
    - name: Include additional variables based on job_type
      include_vars: "group_vars/win2016-cinder-{{ job_type }}" 
      when: job_type is defined
      tags: always

    - name: Include additional variables based on job_type and network_type
      include_vars: "group_vars/win2016-cinder-{{ job_type }}-{{ network_type }}"
      when: network_type is defined
      tags: always

    - include: tasks/windows/join-ad.yaml
      when: join_ad is defined and join_ad

    - include: tasks/windows/configure-smbshare.yaml
      when: smbshare is defined

    - name: Configure services with AD user
      set_fact:
        service_username: "administrator@{{ ad_domain }}"
      when: join_ad is defined and join_ad

    - name: Configure services with local user
      set_fact:
        service_username: "administrator"
      when: join_ad is not defined or not join_ad

    - name: Start services
      win_service:
        name: "{{ item.name }}"
        display_name: "{{ item.name }}"
        description: "{{ item.description }}"
        username: "{{ service_username }}"
        password: "{{ ansible_ssh_pass }}"
        state: restarted
        start_mode: auto
        path: "{{ win_dir.bin }}\\OpenStackService.exe {{ item.name }} {{ item.binary }} --config-file {{ item.config }}"
      with_items: "{{ services }}"
      tags: start-services


- hosts: win2016-compute
  vars_files:
    - zuul-params.yaml
    - group_vars/windows

  tasks:
    - name: Include additional variables based on project
      include_vars: "job_vars/{{ zuul_project | basename }}.yaml"
      failed_when: False 
      tags: always

    - name: Include additional variables based on project job_type
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml"
      when: job_type is defined
      failed_when: False
      tags: always

    - include: tasks/windows/join-ad.yaml
      when: join_ad is defined and join_ad

    - include: tasks/windows/configure-smbshare.yaml
      when: smbshare is defined

    - include: tasks/windows/enable-live-migration.yaml
      when: join_ad is defined and join_ad

    - name: Set neutron hyperv agent service
      set_fact: services={{ services + neutron_hyperv_agent }}
      when: network_type == "hyperv"

    - name: Set neutron ovs agent service
      set_fact: services={{ services + neutron_ovs_agent }}
      when: network_type == "ovs"

    - name: Configure services with AD user
      set_fact:
        service_username: "administrator@{{ ad_domain }}"
        service_password: "{{ ansible_ssh_pass }}"
      when: join_ad is defined and join_ad

    - name: Configure services with local user
      set_fact:
        service_username: "LocalSystem"
        service_password: ""
      when: join_ad is not defined or not join_ad

    - name: Start services
      win_service:
        name: "{{ item.name }}"
        display_name: "{{ item.name }}"
        description: "{{ item.description }}"
        username: "{{ service_username }}"
        password: "{{ service_password }}"
        state: started
        start_mode: auto
        path: "{{ win_dir.bin }}\\OpenStackService.exe {{ item.name }} {{ item.binary }} --config-file {{ item.config }}"
      with_items: "{{ services }}"
      tags: start-services

- hosts: ad
  vars_files:
    - zuul-params.yaml
    - group_vars/windows

  tasks:
    - name: Include additional variables based on project
      include_vars: "job_vars/{{ zuul_project | basename }}.yaml"
      failed_when: False
      tags: always

    - name: Include additional variables based on project job_type
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml"
      when: job_type is defined
      failed_when: False
      tags: always

    - include: tasks/windows/configure-ad-delegation.yaml
      with_items: "{{ win2016_compute_nodes }}"
      loop_control:
        loop_var: compute_node
      when: join_ad is defined and join_ad

- hosts: devstack
  vars_files: 
    - zuul-params.yaml

  tasks:
    - name: Include variables from job_vars/{{ zuul_project | basename }}.yaml
      include_vars: "job_vars/{{ zuul_project | basename }}.yaml"
      failed_when: False
      tags: always 

    - name: Include job_type specific variables
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml"
      when: job_type is defined
      failed_when: False
      tags: always

    - include: tasks/devstack/check-devstack-nova-services.yaml
    - include: tasks/devstack/check-devstack-neutron-services.yaml
    - include: tasks/devstack/check-devstack-cinder-services.yaml
      when: zuul_project == "openstack/cinder" or zuul_project == "openstack/os-brick"

- hosts: win2016-compute
  vars_files:
    - zuul-params.yaml
    - group_vars/windows

  tasks:
    - name: Include additional variables based on project
      include_vars: "job_vars/{{ zuul_project | basename }}.yaml"
      failed_when: False 
      tags: always

    - name: Include additional variables based on project job_type
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml"
      when: job_type is defined
      failed_when: False
      tags: always

    - name: Get neutron_service_check content
      set_fact:
        neutron_service_check: "{{ groups['devstack'] | map('extract', hostvars, 'neutron_service_check') | list}}"
      tags: cns

    - name: Get nova_service_check content
      set_fact:
        nova_service_check: "{{ groups['devstack'] | map('extract', hostvars, 'nova_service_check') | list}}"
      tags: cns

    - name: Get cinder_service_check content
      set_fact:
        cinder_service_check: "{{ groups['devstack'] | map('extract', hostvars, 'cinder_service_check') | list}}"
      when: zuul_project == "openstack/cinder" or zuul_project == "openstack/os-brick"
      tags: cns

    - block:
      - name: Set additional variables if network_type == ovs
        set_fact:
          neutron_agent_type: "{{ item.name }}"
          neutron_binary: "{{ item.binary }}"
          neutron_config: "{{ item.config }}"
        with_items: "{{ neutron_ovs_agent }}"
        when: network_type == "ovs"

      - name: Set additional variables if network_type == hyperv
        set_fact:
          neutron_agent_type: "{{ item.name }}"
          neutron_binary: "{{ item.binary }}"
          neutron_config: "{{ item.config }}"
        with_items: "{{ neutron_hyperv_agent }}"
        when: network_type == "hyperv"

      - name: "Check if {{ neutron_agent_type }}.log is present"
        win_stat:
          path: "{{ win_dir.log }}\\{{ neutron_agent_type }}.log"
          get_checksum: False
        register: neutron_log_stat

      - name: "Run {{ neutron_agent_type }} binary"
        args:
          executable: cmd
        win_shell: |
          "{{ neutron_binary }} --config-file {{ neutron_config }} > {{ win_dir.log }}\\{{ neutron_agent_type }}-stdout.log 2> {{ win_dir.log }}\\{{ neutron_agent_type }}-stderr.log"
        when: neutron_log_stat.stat.exists == False
        ignore_errors: True

      - fail:
          msg: "Neutron agents are down!"
      when: neutron_service_check[0].rc != 0
      tags: cns

    - block:
      - name: Set additional variables for nova service
        set_fact:
          nova_service: "{{ item.name }}"
          nova_binary: "{{ item.binary }}"
          nova_config: "nova.conf"
        loop: "{{ services }}"
        loop_control:
          index_var: service_index
        when: services[service_index].name == 'nova-compute'

      - name: "Check if {{ nova_service }}.log exists"
        win_stat:
          path: "{{ win_dir.log }}\\{{ nova_service }}.log"
          get_checksum: False
        register: nova_log_stat

      - name: "Run {{ nova_binary }} binary"
        args:
          executable: cmd
        win_shell: |
          "{{ nova_binary }} --config-file {{ nova_config }} > {{ win_dir.log }}\\{{ nova_service }}-stdout.log 2> {{ win_dir.log }}\\{{ nova_service }}-stderr.log"
        when: nova_log_stat.stat.exists == False
        ignore_errors: True

      - fail:
          msg: "nova-compute services are down!"
      when: nova_service_check[0].rc != 0
      tags: cns

    - block:
      - name: Set additional variables for cinder-volume service
        set_fact:
          cinder_volume_service: "{{ item.name }}"
          cinder_volume_binary: "{{ item.binary }}"
          cinder_volume_config: "{{ item.config }}"
        loop: "{{ services }}"
        loop_control:
          index_var: service_index
        when: services[service_index].name == 'cinder-volume'

      - name: "Check if {{ cinder_volume_service }} log exists"
        win_stat:
          path: "{{ win_dir.log }}\\cinder.log"
          get_checksum: False
        register: cinder_volume_log_stat

      - name: "Run {{ cinder_volume_binary }} binary"
        args:
          executable: cmd
        win_shell: |
          "{{ cinder_volume_binary }} --config-file {{ cinder_volume_config }} > {{ win_dir.log}}\\{{ cinder_volume_service }}-stdout.log 2> {{ win_dir.log }}\\{{ cinder_volume_service }}-stderr.log"
        when: cinder_volume_log_stat.stat.exists == False
        ignore_errors: True

      - name: Set additional variables for cinder-backup service
        set_fact:
          cinder_backup_service: "{{ item.name }}"
          cinder_backup_binary: "{{ item.binary }}"
          cinder_backup_config: "{{ item.config }}"
        loop: "{{ services }}"
        loop_control:
          index_var: service_index
        when: services[service_index].name == 'cinder-backup'

      - name: "Check if {{ cinder_backup_service }}.log exists"
        win_stat:
          path: "{{ win_dir.log }}\\{{ cinder_backup_service }}.log"
          get_checksum: False
        register: cinder_backup_log_stat

      - name: "Run {{ cinder_backup_binary }} binary"
        args:
          executable: cmd
        win_shell: |
          "{{ cinder_backup_binary }} --config-file {{ cinder_backup_config }} > {{ win_dir.log}}\\{{ cinder_backup_service }}-stdout.log 2> {{ win_dir.log }}\\{{ cinder_backup_service }}-stderr.log"
        when: cinder_backup_log_stat.stat.exists == False
        ignore_errors: True

      - fail:
          msg: "cinder-volume services are down!"
      when: (zuul_project == "openstack/cinder" or zuul_project == "openstack/os-brick") and cinder_service_check[0].rc != 0
      tags: cns

- hosts: devstack
  vars_files: 
    - zuul-params.yaml

  tasks:
    - name: Include variables from job_vars/{{ zuul_project | basename }}.yaml
      include_vars: "job_vars/{{ zuul_project | basename }}.yaml"
      failed_when: False
      tags: always 

    - name: Include job_type specific variables
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml"
      when: job_type is defined
      failed_when: False
      tags: always

    - include: tasks/devstack/discover-hosts.yaml

    - name: Restart nova api
      service:
        name: devstack@n-api
        state: restarted
      become: True

    - name: Create folder {{ devstack_dir.home }}/tempest
      file:
        path: "{{ devstack_dir.home }}/tempest"
        state: directory
        mode: 0755
      tags: run-tests

    - name: Write test list files under {{ devstack_dir.home }}
      copy:
        content: "{{ item.value }}"
        dest: "{{ devstack_dir.home }}/{{ item.key }}.txt"
      with_dict: "{{ tempest_tests }}"
      tags: run-tests

    - name: Upload run-tests.sh
      copy:
        src: files/run-tests.sh
        dest: "{{ devstack_dir.home }}/run-tests.sh"
        mode: 0755
      tags: run-tests

    - name: Run post stack bash script
      shell: "{{ post_stack_bash }}"
      args:
        executable: /bin/bash
      tags: post-stack-bash

    - name: Run tests
      shell: |
        {{ devstack_dir.home }}/run-tests.sh \
        --included-tests {{ devstack_dir.home }}/included-tests.txt \
        --excluded-tests {{ devstack_dir.home }}/excluded-tests.txt \
        --isolated-tests {{ devstack_dir.home }}/isolated-tests.txt \
        > {{ devstack_dir.home }}/tempest/run-tests.sh.log
      register: tempest_result
      when: run_tests is not defined or run_tests
      tags: run-tests
