- hosts: 127.0.0.1
  connection: local
  vars_files: 
    - zuul-params.yaml

  tasks:
    - name: Include variables from job_vars/{{ zuul_project | basename }}.yaml
      include_vars: "job_vars/{{ zuul_project | basename }}.yaml"
      failed_when: False
      tags: always

    - name: Include variables from job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml"
      failed_when: False
      when: job_type is defined
      tags: always

    - include: tasks/boot-instance.yaml
      with_items: "{{ vms }}"
      loop_control:
        loop_var: vm

    - copy: 
        content="{{ vm_data | to_nice_yaml }}"
        dest="{{ work_dir }}/vm-data.yaml"

    - include_vars:
        file: "{{ work_dir }}/vm-data.yaml"
        name: vm_data

    - name: Generate inventory file
      blockinfile:
        path: "{{ inv_file }}"
        create: yes
        block: |
          [{{ item.inventory_group }}]
          {{ vm_data[item.name].ports.management.port.fixed_ips[0].ip_address }} hostname={{ item.name }} {{ item.additional_params }} compute_host={{ vm_data[item.name].server['OS-EXT-SRV-ATTR:host'] }} compute_instance_name={{ vm_data[item.name].server['OS-EXT-SRV-ATTR:instance_name'] }}
        marker: "# {mark} {{ item.name }}"
      with_items: "{{ vms }}"

    - name: Update VLAN range with instance uuid
      shell: "./{{ vlan_range_tool | basename }} -i {{ vlan_range }} -u {{ devstack_uuid }}"
      vars:
        vlan_range_tool: /home/jenkins-slave/vlan_ranges/vlan_range_tool.py
        devstack_uuid: "{{ vm_data[vms | selectattr('devstack', 'defined') | map(attribute='name') | first].server.id }}"
      args:
        chdir: "{{ vlan_range_tool | dirname }}"
      register: update_vlan_range
      until: update_vlan_range.rc == 0
      retries: 3
      delay: 5
      ignore_errors: yes

    - file: state=absent path="{{ log_path }}"
    - file: state=directory path="{{ log_path }}"
    - file: state=directory path="{{ log_path }}/ara-report"
