  # Install zuul in a virtualenv, it messes with pbr and other openstack libraries
  - name: Install zuul version {{ zuul_version }}
    pip:
      virtualenv: "{{ devstack_dir.zuul }}"
      name: "{{ zuul_version }}"
      virtualenv_python: python2.7
    become: True
    tags: install-zuul

  # Workaround for https://github.com/gitpython-developers/GitPython/issues/687
  - name: Update pythongit library to version 2.1.13
    pip:
      virtualenv: "{{ devstack_dir.zuul }}"
      name: "GitPython==2.1.13"
      virtualenv_python: python2.7
    become: True
    tags: install-zuul
