  - name: Install networking-hyperv
    # Explicitly install with environment in shell to keep package editable
    shell: pip3 install -e /opt/stack/networking-hyperv -c /opt/stack/requirements/upper-constraints.txt
    environment:
      SETUPTOOLS_USE_DISTUTILS: stdlib
    become: True
    tags: networking-hyperv
