    - name: Set additional variables if network_type == ovs
      set_fact:
        neutron_agent_type: "{{ item.name }}"
        neutron_binary: "{{ item.binary }}"
        neutron_config: "{{ item.config }}"
      with_items: "{{ neutron_ovs_agent }}"
      when: network_type == "ovs"

    - name: Set additional variables if network_type == hyperv
      set_fact:
        neutron_agent_type: "{{ item.name }}"
        neutron_binary: "{{ item.binary }}"
        neutron_config: "{{ item.config }}"
      with_items: "{{ neutron_hyperv_agent }}"
      when: network_type == "hyperv"

    - name: "Check if {{ neutron_agent_type }}.log is present"
      win_stat:
        path: "{{ win_dir.log }}\\{{ neutron_agent_type }}.log"
        get_checksum: False
      register: neutron_log_stat

    - name: "Run {{ neutron_agent_type }} binary"
      args:
        executable: cmd
      win_shell: |
        "{{ neutron_binary }} --config-file {{ neutron_config }} > {{ win_dir.log }}\\{{ neutron_agent_type }}-stdout.log 2> {{ win_dir.log }}\\{{ neutron_agent_type }}-stderr.log"
      when: neutron_log_stat.stat.exists == False
      ignore_errors: True

    - fail:
        msg: "Neutron agents are down!"