    - name: Set additional variables for cinder-volume service
      set_fact:
        cinder_volume_service: "{{ item.name }}"
        cinder_volume_binary: "{{ item.binary }}"
        cinder_volume_config: "{{ item.config }}"
      loop: "{{ services }}"
      loop_control:
        index_var: service_index
      when: services[service_index].name == 'cinder-volume'

    - name: "Check if {{ cinder_volume_service }} log exists"
      win_stat:
        path: "{{ win_dir.log }}\\cinder.log"
        get_checksum: False
      register: cinder_volume_log_stat

    - name: "Run {{ cinder_volume_binary }} binary"
      args:
        executable: cmd
      win_shell: |
        "{{ cinder_volume_binary }} --config-file {{ cinder_volume_config }} > {{ win_dir.log}}\\{{ cinder_volume_service }}-stdout.log 2> {{ win_dir.log }}\\{{ cinder_volume_service }}-stderr.log"
      when: cinder_volume_log_stat.stat.exists == False
      ignore_errors: True

    - name: Set additional variables for cinder-backup service
      set_fact:
        cinder_backup_service: "{{ item.name }}"
        cinder_backup_binary: "{{ item.binary }}"
        cinder_backup_config: "{{ item.config }}"
      loop: "{{ services }}"
      loop_control:
        index_var: service_index
      when: services[service_index].name == 'cinder-backup'

    - name: "Check if {{ cinder_backup_service }}.log exists"
      win_stat:
        path: "{{ win_dir.log }}\\{{ cinder_backup_service }}.log"
        get_checksum: False
      register: cinder_backup_log_stat

    - name: "Run {{ cinder_backup_binary }} binary"
      args:
        executable: cmd
      win_shell: |
        "{{ cinder_backup_binary }} --config-file {{ cinder_backup_config }} > {{ win_dir.log}}\\{{ cinder_backup_service }}-stdout.log 2> {{ win_dir.log }}\\{{ cinder_backup_service }}-stderr.log"
      when: cinder_backup_log_stat.stat.exists == False
      ignore_errors: True

    - fail:
        msg: "cinder-volume services are down!"