    - name: Set additional variables for nova service
      set_fact:
        nova_service: "{{ item.name }}"
        nova_binary: "{{ item.binary }}"
        nova_config: "{{ item.config }}"
      loop: "{{ services }}"
      loop_control:
        index_var: service_index
      when: services[service_index].name == 'nova-compute'

    - name: "Check if {{ nova_service }}.log exists"
      win_stat:
        path: "{{ win_dir.log }}\\{{ nova_service }}.log"
        get_checksum: False
      register: nova_log_stat

    - name: "Run {{ nova_binary }} binary"
      args:
        executable: cmd
      win_shell: |
        "{{ nova_binary }} --config-file {{ nova_config }} > {{ win_dir.log }}\\{{ nova_service }}-stdout.log 2> {{ win_dir.log }}\\{{ nova_service }}-stderr.log"
      when: nova_log_stat.stat.exists == False
      ignore_errors: True

    - fail:
        msg: "nova-compute services are down!"